{% set name = "xarray-safe-s1" %}
{% set version = "2023.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-safe-s1-{{ version }}.tar.gz
  sha256: fe5216bc770e66c5ab51d5d246c2263029b675d0a81d09aada9a7a1adbaa6f76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - geopandas
    - numpy
    - xarray
    - xarray-datatree
    - rasterio
    - rioxarray
    - lxml
    - jmespath
    - fsspec
    - pandas
    - shapely
    - pyproj
    - dask-core
    - affine
    - aiohttp

test:
  imports:
    - safe_s1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xarray-safe-s1/
  summary: Sentinel-1 SAR ESA - Copernicus mission python - xarray reader
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/umr-lops/xarray-safe-s1/
  doc_url: https://xarray-safe-s1.readthedocs.io/en/latest/
extra:
  recipe-maintainers:
    - yreynaud
    - agrouaze
